// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXH4dDp5eHRGc7Kfe0iifnLkpTcdC3VAI',
    appId: '1:139060751797:web:f19dfc9e1f9736fc80bdfc',
    messagingSenderId: '139060751797',
    projectId: 'gross-application',
    authDomain: 'gross-application.firebaseapp.com',
    storageBucket: 'gross-application.firebasestorage.app',
    measurementId: 'G-98ME04XZLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXbPbSoNHcuaL6j5BRzUo4FQMwEmy0YOI',
    appId: '1:139060751797:android:dac9e10e4f81c1cf80bdfc',
    messagingSenderId: '139060751797',
    projectId: 'gross-application',
    storageBucket: 'gross-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcJsu_VM4wosqe0KDIShKQDI0ceF2Tfvw',
    appId: '1:139060751797:ios:86878ddc9da1fecf80bdfc',
    messagingSenderId: '139060751797',
    projectId: 'gross-application',
    storageBucket: 'gross-application.firebasestorage.app',
    iosBundleId: 'com.example.groceryApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcJsu_VM4wosqe0KDIShKQDI0ceF2Tfvw',
    appId: '1:139060751797:ios:86878ddc9da1fecf80bdfc',
    messagingSenderId: '139060751797',
    projectId: 'gross-application',
    storageBucket: 'gross-application.firebasestorage.app',
    iosBundleId: 'com.example.groceryApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXH4dDp5eHRGc7Kfe0iifnLkpTcdC3VAI',
    appId: '1:139060751797:web:294a7f89e056416980bdfc',
    messagingSenderId: '139060751797',
    projectId: 'gross-application',
    authDomain: 'gross-application.firebaseapp.com',
    storageBucket: 'gross-application.firebasestorage.app',
    measurementId: 'G-CLXVC6HC9L',
  );
}
