// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD05PgSYig03dBHSjrsjogIbufzd71ctsg',
    appId: '1:815825452900:web:7c54dbc0ec7e34f6cf0471',
    messagingSenderId: '815825452900',
    projectId: 'grocerystore-6d730',
    authDomain: 'grocerystore-6d730.firebaseapp.com',
    storageBucket: 'grocerystore-6d730.firebasestorage.app',
    measurementId: 'G-E08DML7C4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDycVL-aeHYgaLyxICeVAfN5D4kO2udM7M',
    appId: '1:815825452900:android:3467bd267c207aa8cf0471',
    messagingSenderId: '815825452900',
    projectId: 'grocerystore-6d730',
    storageBucket: 'grocerystore-6d730.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiP0ErbPfelUiQv7LK5pjm6rVhtv17enQ',
    appId: '1:815825452900:ios:d3654b287ce9682bcf0471',
    messagingSenderId: '815825452900',
    projectId: 'grocerystore-6d730',
    storageBucket: 'grocerystore-6d730.firebasestorage.app',
    iosBundleId: 'com.example.groceryApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiP0ErbPfelUiQv7LK5pjm6rVhtv17enQ',
    appId: '1:815825452900:ios:d3654b287ce9682bcf0471',
    messagingSenderId: '815825452900',
    projectId: 'grocerystore-6d730',
    storageBucket: 'grocerystore-6d730.firebasestorage.app',
    iosBundleId: 'com.example.groceryApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD05PgSYig03dBHSjrsjogIbufzd71ctsg',
    appId: '1:815825452900:web:b19ec049aa0648f9cf0471',
    messagingSenderId: '815825452900',
    projectId: 'grocerystore-6d730',
    authDomain: 'grocerystore-6d730.firebaseapp.com',
    storageBucket: 'grocerystore-6d730.firebasestorage.app',
    measurementId: 'G-1D64C66E04',
  );
}
